[project]
name = "arxivdb"
version = "0.2.0"
description = "Code to convert the [arXiv Dataset](https://www.kaggle.com/datasets/Cornell-University/arxiv) from JSON to an SQLite3 database"
authors = [{ name = "Nicholas M. Synovic", email = "nicholas.synovic@gmail.com" }]
requires-python = "~=3.13"
readme = "README.md"
keywords = [
    "Dataset",
    "arXiv",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: SQL",
    "Topic :: Database",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Information Analysis",
]
dependencies = [
    "kaggle>=1.6.17,<2",
    "sqlalchemy>=2.0.32,<3",
    "pandas>=2.2.2,<3",
    "progress~=1.6",
    "click>=8.1.7,<9",
    "pydantic>=2.11.7",
]

[project.urls]
Homepage = "https://github.com/NicholasSynovic/tool_arXiv-db"
Repository = "https://github.com/NicholasSynovic/tool_arXiv-db"

[project.scripts]
arxivdb = "arxivdb.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
